version: '3.8'

services:
  pyspark-notebook:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark_notebook
    ports:
      - "8888:8888"  
    volumes:
      - ./:/home/jovyan/work  
    environment:
      JUPYTER_TOKEN: "111203"  
      GRANT_SUDO: "yes"  
    networks:
      kafkanet:
        ipv4_address: 172.25.0.11

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      kafkanet:
        ipv4_address: 172.25.0.12
  kafka:
    image: confluentinc/cp-kafka:7.3.2
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 172.25.0.12:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      kafkanet:
        ipv4_address: 172.25.0.13

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8087:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
      - zookeeper
    networks:
      kafkanet:
        ipv4_address: 172.25.0.14

  mongo:
    image: mongo
    container_name: mongo-container
    ports:
    - 27017:27017
    volumes: 
    - './mongodb:/data/db'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      kafkanet:
        ipv4_address: 172.25.0.15

  mongo-express:
    image: mongo-express
    container_name: mongo-express_container
    restart: always
    ports:
    - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      kafkanet:
        ipv4_address: 172.25.0.16

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_ENV=production
      - SUPERSET_SECRET_KEY=yoursecretkey
      - FLASK_ENV=development
      - DATABASE_URL=postgresql+psycopg2://superset:superset@db:5432/superset
    ports:
      - "8088:8088"
    depends_on:
      - db
    volumes:
      - ./superset_home:/app/superset_home
    networks:
      kafkanet:
        ipv4_address: 172.25.0.17


  db:
    image: postgres:13
    container_name: superset_db
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      kafkanet:
        ipv4_address: 172.25.0.18

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8091:80"
    depends_on:
      - db
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    networks:
      kafkanet:
        ipv4_address: 172.25.0.19


networks:
  kafkanet:
    name: kafkanet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16

